
package com.lsh.wms.integration.wumart.obdaccount;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Z_DELIVERY_OUTBOUND_UPDATE", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/home/work/wumart/obdaccount.wsdl")
public class ZDELIVERYOUTBOUNDUPDATE_Service
    extends Service
{

    private final static URL ZDELIVERYOUTBOUNDUPDATE_WSDL_LOCATION;
    private final static WebServiceException ZDELIVERYOUTBOUNDUPDATE_EXCEPTION;
    private final static QName ZDELIVERYOUTBOUNDUPDATE_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "Z_DELIVERY_OUTBOUND_UPDATE");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/work/wumart/obdaccount.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZDELIVERYOUTBOUNDUPDATE_WSDL_LOCATION = url;
        ZDELIVERYOUTBOUNDUPDATE_EXCEPTION = e;
    }

    public ZDELIVERYOUTBOUNDUPDATE_Service() {
        super(__getWsdlLocation(), ZDELIVERYOUTBOUNDUPDATE_QNAME);
    }

    public ZDELIVERYOUTBOUNDUPDATE_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZDELIVERYOUTBOUNDUPDATE_QNAME, features);
    }

    public ZDELIVERYOUTBOUNDUPDATE_Service(URL wsdlLocation) {
        super(wsdlLocation, ZDELIVERYOUTBOUNDUPDATE_QNAME);
    }

    public ZDELIVERYOUTBOUNDUPDATE_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZDELIVERYOUTBOUNDUPDATE_QNAME, features);
    }

    public ZDELIVERYOUTBOUNDUPDATE_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZDELIVERYOUTBOUNDUPDATE_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZDELIVERYOUTBOUNDUPDATE
     */
    @WebEndpoint(name = "binding")
    public ZDELIVERYOUTBOUNDUPDATE getBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding"), ZDELIVERYOUTBOUNDUPDATE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZDELIVERYOUTBOUNDUPDATE
     */
    @WebEndpoint(name = "binding")
    public ZDELIVERYOUTBOUNDUPDATE getBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding"), ZDELIVERYOUTBOUNDUPDATE.class, features);
    }

    /**
     * 
     * @return
     *     returns ZDELIVERYOUTBOUNDUPDATE
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZDELIVERYOUTBOUNDUPDATE getBindingSOAP12() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding_SOAP12"), ZDELIVERYOUTBOUNDUPDATE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZDELIVERYOUTBOUNDUPDATE
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZDELIVERYOUTBOUNDUPDATE getBindingSOAP12(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding_SOAP12"), ZDELIVERYOUTBOUNDUPDATE.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZDELIVERYOUTBOUNDUPDATE_EXCEPTION!= null) {
            throw ZDELIVERYOUTBOUNDUPDATE_EXCEPTION;
        }
        return ZDELIVERYOUTBOUNDUPDATE_WSDL_LOCATION;
    }

}
