
package com.lsh.wms.integration.wumart.soobd;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Z_BAPI_R2_DELIVERY_SO", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/home/wms/wumart/soObd.wsdl")
public class ZBAPIR2DELIVERYSO_Service
    extends Service
{

    private final static URL ZBAPIR2DELIVERYSO_WSDL_LOCATION;
    private final static WebServiceException ZBAPIR2DELIVERYSO_EXCEPTION;
    private final static QName ZBAPIR2DELIVERYSO_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "Z_BAPI_R2_DELIVERY_SO");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/wms/wumart/soObd.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZBAPIR2DELIVERYSO_WSDL_LOCATION = url;
        ZBAPIR2DELIVERYSO_EXCEPTION = e;
    }

    public ZBAPIR2DELIVERYSO_Service() {
        super(__getWsdlLocation(), ZBAPIR2DELIVERYSO_QNAME);
    }

    public ZBAPIR2DELIVERYSO_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZBAPIR2DELIVERYSO_QNAME, features);
    }

    public ZBAPIR2DELIVERYSO_Service(URL wsdlLocation) {
        super(wsdlLocation, ZBAPIR2DELIVERYSO_QNAME);
    }

    public ZBAPIR2DELIVERYSO_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZBAPIR2DELIVERYSO_QNAME, features);
    }

    public ZBAPIR2DELIVERYSO_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZBAPIR2DELIVERYSO_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZBAPIR2DELIVERYSO
     */
    @WebEndpoint(name = "binding")
    public ZBAPIR2DELIVERYSO getBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding"), ZBAPIR2DELIVERYSO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZBAPIR2DELIVERYSO
     */
    @WebEndpoint(name = "binding")
    public ZBAPIR2DELIVERYSO getBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding"), ZBAPIR2DELIVERYSO.class, features);
    }

    /**
     * 
     * @return
     *     returns ZBAPIR2DELIVERYSO
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZBAPIR2DELIVERYSO getBindingSOAP12() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding_SOAP12"), ZBAPIR2DELIVERYSO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZBAPIR2DELIVERYSO
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZBAPIR2DELIVERYSO getBindingSOAP12(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding_SOAP12"), ZBAPIR2DELIVERYSO.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZBAPIR2DELIVERYSO_EXCEPTION!= null) {
            throw ZBAPIR2DELIVERYSO_EXCEPTION;
        }
        return ZBAPIR2DELIVERYSO_WSDL_LOCATION;
    }

}
