
package com.lsh.wms.integration.wumart.soobd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Z_BAPI_R2_DELIVERY_SO", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZBAPIR2DELIVERYSO {


    /**
     * 
     * @param _return
     * @param obdheader
     * @param obditem
     * @return
     *     returns com.lsh.wms.integration.wumart.soobd.TABLEOFBAPIRET2
     */
    @WebMethod(operationName = "Z_BAPI_R2_DELIVERY_SO")
    @WebResult(name = "RETURN", targetNamespace = "")
    @RequestWrapper(localName = "Z_BAPI_R2_DELIVERY_SO", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.lsh.wms.integration.wumart.soobd.ZBAPIR2DELIVERYSO_Type")
    @ResponseWrapper(localName = "Z_BAPI_R2_DELIVERY_SOResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.lsh.wms.integration.wumart.soobd.ZBAPIR2DELIVERYSOResponse")
    public TABLEOFBAPIRET2 zBAPIR2DELIVERYSO(
        @WebParam(name = "OBDHEADER", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TABLEOFZBAPIR2DELIVERYHEAD> obdheader,
        @WebParam(name = "OBDITEM", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TABLEOFZBAPIR2DELIVERYITEM> obditem,
        @WebParam(name = "RETURN", targetNamespace = "")
        TABLEOFBAPIRET2 _return);

}
