
package com.lsh.wms.integration.wumart.ibdback;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZBAPI_GOODSMVT_CANCEL", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZBAPIGOODSMVTCANCEL {


    /**
     * 
     * @param pDOCITEM
     * @param pHEADRET
     * @param _return
     * @param pDOCYEAR
     * @param pDATE
     * @param pUNAME
     * @param pDOCUMENT
     * @return
     *     returns com.lsh.wms.integration.wumart.ibdback.TABLEOFBAPIRET2
     */
    @WebMethod(operationName = "ZBAPI_GOODSMVT_CANCEL")
    @WebResult(name = "RETURN", targetNamespace = "")
    @RequestWrapper(localName = "ZBAPI_GOODSMVT_CANCEL", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.lsh.wms.integration.wumart.ibdback.ZBAPIGOODSMVTCANCEL_Type")
    @ResponseWrapper(localName = "ZBAPI_GOODSMVT_CANCELResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.lsh.wms.integration.wumart.ibdback.ZBAPIGOODSMVTCANCELResponse")
    public TABLEOFBAPIRET2 zbapiGOODSMVTCANCEL(
        @WebParam(name = "P_DATE", targetNamespace = "")
        XMLGregorianCalendar pDATE,
        @WebParam(name = "P_DOCITEM", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TABLEOFBAPI2017GMITEM04> pDOCITEM,
        @WebParam(name = "P_DOCUMENT", targetNamespace = "")
        String pDOCUMENT,
        @WebParam(name = "P_DOCYEAR", targetNamespace = "")
        String pDOCYEAR,
        @WebParam(name = "P_UNAME", targetNamespace = "")
        String pUNAME,
        @WebParam(name = "RETURN", targetNamespace = "")
        TABLEOFBAPIRET2 _return,
        @WebParam(name = "P_HEADRET", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<BAPI2017GMHEADRET> pHEADRET);

}
