package com.lsh.wms.integration.wumart.stockmoving;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2016-12-01T16:06:25.235+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "ZBAPI_GOODSMVT_CREATE_01", 
                  wsdlLocation = "file:/home/work/wumart/1234.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style") 
public class ZBAPIGOODSMVTCREATE01_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBAPI_GOODSMVT_CREATE_01");
    public final static QName Binding = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding");
    public final static QName BindingSOAP12 = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding_SOAP12");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/work/wumart/1234.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZBAPIGOODSMVTCREATE01_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/SAP-WS/1234.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZBAPIGOODSMVTCREATE01_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZBAPIGOODSMVTCREATE01_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZBAPIGOODSMVTCREATE01_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZBAPIGOODSMVTCREATE01_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZBAPIGOODSMVTCREATE01_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZBAPIGOODSMVTCREATE01_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ZBAPIGOODSMVTCREATE01
     */
    @WebEndpoint(name = "binding")
    public ZBAPIGOODSMVTCREATE01 getBinding() {
        return super.getPort(Binding, ZBAPIGOODSMVTCREATE01.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZBAPIGOODSMVTCREATE01
     */
    @WebEndpoint(name = "binding")
    public ZBAPIGOODSMVTCREATE01 getBinding(WebServiceFeature... features) {
        return super.getPort(Binding, ZBAPIGOODSMVTCREATE01.class, features);
    }
    /**
     *
     * @return
     *     returns ZBAPIGOODSMVTCREATE01
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZBAPIGOODSMVTCREATE01 getBindingSOAP12() {
        return super.getPort(BindingSOAP12, ZBAPIGOODSMVTCREATE01.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZBAPIGOODSMVTCREATE01
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZBAPIGOODSMVTCREATE01 getBindingSOAP12(WebServiceFeature... features) {
        return super.getPort(BindingSOAP12, ZBAPIGOODSMVTCREATE01.class, features);
    }

}
