package com.lsh.wms.integration.wumart.stockmoving;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2016-12-01T16:06:25.226+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZBAPI_GOODSMVT_CREATE_01")
@XmlSeeAlso({ObjectFactory.class})
public interface ZBAPIGOODSMVTCREATE01 {

    @RequestWrapper(localName = "ZbapiGoodsmvtCreate01", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.ZbapiGoodsmvtCreate01_Type")
    @WebMethod(operationName = "ZbapiGoodsmvtCreate01")
    @ResponseWrapper(localName = "ZbapiGoodsmvtCreate01Response", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.ZbapiGoodsmvtCreate01Response")
    public void zbapiGoodsmvtCreate01(
            @WebParam(mode = WebParam.Mode.INOUT, name = "Extensionin", targetNamespace = "")
                    javax.xml.ws.Holder<TableOfBapiparex> extensionin,
            @WebParam(name = "GoodsmvtCode", targetNamespace = "")
                    Bapi2017GmCode goodsmvtCode,
            @WebParam(name = "GoodsmvtHeader", targetNamespace = "")
                    Bapi2017GmHead01 goodsmvtHeader,
            @WebParam(mode = WebParam.Mode.INOUT, name = "GoodsmvtItem", targetNamespace = "")
                    javax.xml.ws.Holder<TableOfBapi2017GmItemCreate> goodsmvtItem,
            @WebParam(mode = WebParam.Mode.INOUT, name = "GoodsmvtItemCwm", targetNamespace = "")
                    javax.xml.ws.Holder<TableOfCwmBapi2017GmItemCreate> goodsmvtItemCwm,
            @WebParam(name = "GoodsmvtRefEwm", targetNamespace = "")
                    SpeBapi2017GmRefEwm goodsmvtRefEwm,
            @WebParam(mode = WebParam.Mode.INOUT, name = "GoodsmvtSerialnumber", targetNamespace = "")
                    javax.xml.ws.Holder<TableOfBapi2017GmSerialnumber> goodsmvtSerialnumber,
            @WebParam(mode = WebParam.Mode.INOUT, name = "GoodsmvtServPartData", targetNamespace = "")
                    javax.xml.ws.Holder<TableOfSpeBapi2017ServicepartData> goodsmvtServPartData,
            @WebParam(mode = WebParam.Mode.INOUT, name = "Return", targetNamespace = "")
                    javax.xml.ws.Holder<TableOfBapiret2> _return,
            @WebParam(name = "Testrun", targetNamespace = "")
                    String testrun,
            @WebParam(mode = WebParam.Mode.OUT, name = "GoodsmvtHeadret", targetNamespace = "")
                    javax.xml.ws.Holder<Bapi2017GmHeadRet> goodsmvtHeadret,
            @WebParam(mode = WebParam.Mode.OUT, name = "Matdocumentyear", targetNamespace = "")
                    javax.xml.ws.Holder<String> matdocumentyear,
            @WebParam(mode = WebParam.Mode.OUT, name = "Materialdocument", targetNamespace = "")
                    javax.xml.ws.Holder<String> materialdocument
    );
}
