
package com.lsh.wms.integration.wumart.newibdaccount;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Z_DELIVERY_INBOUND_UPDATE", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/home/wms/wumart/ibdaccount.wsdl")
public class ZDELIVERYINBOUNDUPDATE_Service
    extends Service
{

    private final static URL ZDELIVERYINBOUNDUPDATE_WSDL_LOCATION;
    private final static WebServiceException ZDELIVERYINBOUNDUPDATE_EXCEPTION;
    private final static QName ZDELIVERYINBOUNDUPDATE_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "Z_DELIVERY_INBOUND_UPDATE");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/wms/wumart/ibdaccount.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZDELIVERYINBOUNDUPDATE_WSDL_LOCATION = url;
        ZDELIVERYINBOUNDUPDATE_EXCEPTION = e;
    }

    public ZDELIVERYINBOUNDUPDATE_Service() {
        super(__getWsdlLocation(), ZDELIVERYINBOUNDUPDATE_QNAME);
    }

    public ZDELIVERYINBOUNDUPDATE_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZDELIVERYINBOUNDUPDATE_QNAME, features);
    }

    public ZDELIVERYINBOUNDUPDATE_Service(URL wsdlLocation) {
        super(wsdlLocation, ZDELIVERYINBOUNDUPDATE_QNAME);
    }

    public ZDELIVERYINBOUNDUPDATE_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZDELIVERYINBOUNDUPDATE_QNAME, features);
    }

    public ZDELIVERYINBOUNDUPDATE_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZDELIVERYINBOUNDUPDATE_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZDELIVERYINBOUNDUPDATE
     */
    @WebEndpoint(name = "binding")
    public ZDELIVERYINBOUNDUPDATE getBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding"), ZDELIVERYINBOUNDUPDATE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZDELIVERYINBOUNDUPDATE
     */
    @WebEndpoint(name = "binding")
    public ZDELIVERYINBOUNDUPDATE getBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding"), ZDELIVERYINBOUNDUPDATE.class, features);
    }

    /**
     * 
     * @return
     *     returns ZDELIVERYINBOUNDUPDATE
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZDELIVERYINBOUNDUPDATE getBindingSOAP12() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding_SOAP12"), ZDELIVERYINBOUNDUPDATE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZDELIVERYINBOUNDUPDATE
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZDELIVERYINBOUNDUPDATE getBindingSOAP12(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding_SOAP12"), ZDELIVERYINBOUNDUPDATE.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZDELIVERYINBOUNDUPDATE_EXCEPTION!= null) {
            throw ZDELIVERYINBOUNDUPDATE_EXCEPTION;
        }
        return ZDELIVERYINBOUNDUPDATE_WSDL_LOCATION;
    }

}
