
package com.lsh.wms.integration.wumart.account;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZBAPI_MATERIAL_GET_DETAIL", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/home/work/wumart/account.wsdl")
public class ZBAPIMATERIALGETDETAIL_Service
    extends Service
{

    private final static URL ZBAPIMATERIALGETDETAIL_WSDL_LOCATION;
    private final static WebServiceException ZBAPIMATERIALGETDETAIL_EXCEPTION;
    private final static QName ZBAPIMATERIALGETDETAIL_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZBAPI_MATERIAL_GET_DETAIL");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/work/wumart/account.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZBAPIMATERIALGETDETAIL_WSDL_LOCATION = url;
        ZBAPIMATERIALGETDETAIL_EXCEPTION = e;
    }

    public ZBAPIMATERIALGETDETAIL_Service() {
        super(__getWsdlLocation(), ZBAPIMATERIALGETDETAIL_QNAME);
    }

    public ZBAPIMATERIALGETDETAIL_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZBAPIMATERIALGETDETAIL_QNAME, features);
    }

    public ZBAPIMATERIALGETDETAIL_Service(URL wsdlLocation) {
        super(wsdlLocation, ZBAPIMATERIALGETDETAIL_QNAME);
    }

    public ZBAPIMATERIALGETDETAIL_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZBAPIMATERIALGETDETAIL_QNAME, features);
    }

    public ZBAPIMATERIALGETDETAIL_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZBAPIMATERIALGETDETAIL_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZBAPIMATERIALGETDETAIL
     */
    @WebEndpoint(name = "binding")
    public ZBAPIMATERIALGETDETAIL getBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding"), ZBAPIMATERIALGETDETAIL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZBAPIMATERIALGETDETAIL
     */
    @WebEndpoint(name = "binding")
    public ZBAPIMATERIALGETDETAIL getBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding"), ZBAPIMATERIALGETDETAIL.class, features);
    }

    /**
     * 
     * @return
     *     returns ZBAPIMATERIALGETDETAIL
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZBAPIMATERIALGETDETAIL getBindingSOAP12() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding_SOAP12"), ZBAPIMATERIALGETDETAIL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZBAPIMATERIALGETDETAIL
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZBAPIMATERIALGETDETAIL getBindingSOAP12(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding_SOAP12"), ZBAPIMATERIALGETDETAIL.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZBAPIMATERIALGETDETAIL_EXCEPTION!= null) {
            throw ZBAPIMATERIALGETDETAIL_EXCEPTION;
        }
        return ZBAPIMATERIALGETDETAIL_WSDL_LOCATION;
    }

}
