
package com.lsh.wms.integration.wumart.account;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZBAPI_MATERIAL_GET_DETAIL", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZBAPIMATERIALGETDETAIL {


    /**
     * 
     * @param materialvaluationdata
     * @param plant
     * @param materialGeneralData
     * @param materialEvg
     * @param valuationtype
     * @param materialplantdata
     * @param valuationarea
     * @param material
     * @return
     *     returns com.lsh.wms.integration.wumart.account.Bapireturn
     */
    @WebMethod(operationName = "MaterialGetDetail")
    @WebResult(name = "Return", targetNamespace = "")
    @RequestWrapper(localName = "MaterialGetDetail", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.lsh.wms.integration.wumart.account.MaterialGetDetail")
    @ResponseWrapper(localName = "MaterialGetDetailResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.lsh.wms.integration.wumart.account.MaterialGetDetailResponse")
    public Bapireturn materialGetDetail(
        @WebParam(name = "Material", targetNamespace = "")
        String material,
        @WebParam(name = "MaterialEvg", targetNamespace = "")
        Bapimgvmatnr materialEvg,
        @WebParam(name = "Plant", targetNamespace = "")
        String plant,
        @WebParam(name = "Valuationarea", targetNamespace = "")
        String valuationarea,
        @WebParam(name = "Valuationtype", targetNamespace = "")
        String valuationtype,
        @WebParam(name = "MaterialGeneralData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Bapimatdoa> materialGeneralData,
        @WebParam(name = "Materialplantdata", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Bapimatdoc> materialplantdata,
        @WebParam(name = "Materialvaluationdata", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Bapimatdobew> materialvaluationdata);

}
