
package com.lsh.wms.integration.wumart.ibd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZMM_INB_IBD", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZMMINBIBD {


    /**
     * 
     * @param isInbDeliveryHeader
     * @param itInbDeliveryDetail
     * @param efDelivery
     * @param _return
     * @return
     *     returns com.lsh.wms.integration.wumart.ibd.TableOfBapireturn
     */
    @WebMethod(operationName = "ZbapiBbpInbIbd")
    @WebResult(name = "Return", targetNamespace = "")
    @RequestWrapper(localName = "ZbapiBbpInbIbd", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.lsh.wms.integration.wumart.ibd.ZbapiBbpInbIbd")
    @ResponseWrapper(localName = "ZbapiBbpInbIbdResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.lsh.wms.integration.wumart.ibd.ZbapiBbpInbIbdResponse")
    public TableOfBapireturn zbapiBbpInbIbd(
        @WebParam(name = "IsInbDeliveryHeader", targetNamespace = "")
        BbpInbdL isInbDeliveryHeader,
        @WebParam(name = "ItInbDeliveryDetail", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfBbpInbdD> itInbDeliveryDetail,
        @WebParam(name = "Return", targetNamespace = "")
        TableOfBapireturn _return,
        @WebParam(name = "EfDelivery", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> efDelivery);

}
